import {
  customerCounterpartyAssignments,
  counterpartyCountryCodeEnum,
  counterpartyGroupMemberships,
  counterpartyGroups,
  counterparties,
  counterpartyKindEnum,
  counterpartyRelationshipKindEnum,
} from "./counterparties/adapters/drizzle/schema";
import { customers } from "./customers/adapters/drizzle/schema";
import {
  partyAddresses,
  partyContacts,
  partyIdentifiers,
  partyProfiles,
  partyLicenses,
  partyRepresentatives,
} from "./party-profiles/adapters/drizzle/schema";
import {
  organizations,
  partyCountryCodeEnum,
  partyKindEnum,
} from "./organizations/adapters/drizzle/schema";
import {
  organizationRequisiteBindings,
  requisiteKindEnum,
  requisiteOwnerTypeEnum,
  requisiteIdentifiers,
  requisiteProviderBranchIdentifiers,
  requisiteProviderBranches,
  requisiteProviderIdentifiers,
  requisiteProviders,
  requisites,
} from "./requisites/adapters/drizzle/schema";
import { subAgentProfiles } from "./sub-agent-profiles/adapters/drizzle/schema";

export {
  counterparties,
  counterpartyCountryCodeEnum,
  customerCounterpartyAssignments,
  counterpartyGroupMemberships,
  counterpartyGroups,
  counterpartyKindEnum,
  counterpartyRelationshipKindEnum,
  customers,
  organizations,
  partyAddresses,
  partyCountryCodeEnum,
  partyContacts,
  partyKindEnum,
  partyIdentifiers,
  partyProfiles,
  partyLicenses,
  partyRepresentatives,
  organizationRequisiteBindings,
  requisiteIdentifiers,
  requisiteKindEnum,
  requisiteOwnerTypeEnum,
  requisiteProviderBranchIdentifiers,
  requisiteProviderBranches,
  requisiteProviderIdentifiers,
  requisiteProviders,
  requisites,
  subAgentProfiles,
};

export const schema = {
  customers,
  partyKindEnum,
  partyCountryCodeEnum,
  organizations,
  counterpartyKindEnum,
  counterpartyCountryCodeEnum,
  counterparties,
  partyProfiles,
  partyIdentifiers,
  partyAddresses,
  partyContacts,
  partyRepresentatives,
  partyLicenses,
  customerCounterpartyAssignments,
  counterpartyGroups,
  counterpartyGroupMemberships,
  counterpartyRelationshipKindEnum,
  requisiteOwnerTypeEnum,
  requisiteKindEnum,
  requisiteProviders,
  requisiteProviderIdentifiers,
  requisiteProviderBranches,
  requisiteProviderBranchIdentifiers,
  requisites,
  requisiteIdentifiers,
  organizationRequisiteBindings,
  subAgentProfiles,
};
