export const DOCUMENT_MODULE_ID = {
    TRANSFER: "transfer",
    TRANSFER_SETTLE: "transfer_settle",
    TRANSFER_VOID: "transfer_void",
    PAYMENT_CASE: "payment_case",
    PAYIN_FUNDING: "payin_funding",
    FX_EXECUTE: "fx_execute",
    PAYOUT_INITIATE: "payout_initiate",
    PAYOUT_SETTLE: "payout_settle",
    PAYOUT_VOID: "payout_void",
    FEE_PAYOUT_INITIATE: "fee_payout_initiate",
    FEE_PAYOUT_SETTLE: "fee_payout_settle",
    FEE_PAYOUT_VOID: "fee_payout_void",
    EXTERNAL_FUNDING: "external_funding",
};
export const OPERATION_CODE = {
    TRANSFER_APPROVE_IMMEDIATE_INTRA: "TRANSFER_APPROVE_IMMEDIATE_INTRA",
    TRANSFER_APPROVE_PENDING_INTRA: "TRANSFER_APPROVE_PENDING_INTRA",
    TRANSFER_APPROVE_IMMEDIATE_CROSS: "TRANSFER_APPROVE_IMMEDIATE_CROSS",
    TRANSFER_APPROVE_PENDING_CROSS: "TRANSFER_APPROVE_PENDING_CROSS",
    TRANSFER_SETTLE_PENDING: "TRANSFER_SETTLE_PENDING",
    TRANSFER_VOID_PENDING: "TRANSFER_VOID_PENDING",
    TREASURY_FUNDING_SETTLED: "TREASURY_FUNDING_SETTLED",
    TREASURY_EXTERNAL_FUNDING: "TREASURY_EXTERNAL_FUNDING",
    TREASURY_FX_EXECUTED: "TREASURY_FX_EXECUTED",
    TREASURY_PAYOUT_INIT: "TREASURY_PAYOUT_INIT",
    TREASURY_PAYOUT_SETTLE: "TREASURY_PAYOUT_SETTLE",
    TREASURY_PAYOUT_VOID: "TREASURY_PAYOUT_VOID",
    TREASURY_FEE_PAYMENT_INIT: "TREASURY_FEE_PAYMENT_INIT",
    TREASURY_FEE_PAYMENT_SETTLE: "TREASURY_FEE_PAYMENT_SETTLE",
    TREASURY_FEE_PAYMENT_VOID: "TREASURY_FEE_PAYMENT_VOID",
};
export const POSTING_TEMPLATE_KEY = {
    TRANSFER_INTRA_IMMEDIATE: "transfer.intra.immediate",
    TRANSFER_INTRA_PENDING: "transfer.intra.pending",
    TRANSFER_CROSS_SOURCE_IMMEDIATE: "transfer.cross.source.immediate",
    TRANSFER_CROSS_SOURCE_PENDING: "transfer.cross.source.pending",
    TRANSFER_CROSS_DESTINATION_IMMEDIATE: "transfer.cross.destination.immediate",
    TRANSFER_CROSS_DESTINATION_PENDING: "transfer.cross.destination.pending",
    TRANSFER_PENDING_SETTLE: "transfer.pending.settle",
    TRANSFER_PENDING_VOID: "transfer.pending.void",
    EXTERNAL_FUNDING_FOUNDER_EQUITY: "external_funding.founder_equity",
    EXTERNAL_FUNDING_INVESTOR_EQUITY: "external_funding.investor_equity",
    EXTERNAL_FUNDING_SHAREHOLDER_LOAN: "external_funding.shareholder_loan",
    EXTERNAL_FUNDING_OPENING_BALANCE: "external_funding.opening_balance",
    PAYMENT_PAYIN_FUNDING: "payment.payin_funding",
    PAYMENT_FX_PRINCIPAL: "payment.fx.principal",
    PAYMENT_FX_LEG_OUT: "payment.fx.leg_out",
    PAYMENT_FX_LEG_IN: "payment.fx.leg_in",
    PAYMENT_FX_FEE_INCOME: "payment.fx.fee_income",
    PAYMENT_FX_SPREAD_INCOME: "payment.fx.spread_income",
    PAYMENT_FX_FEE_RESERVE: "payment.fx.fee_reserve",
    PAYMENT_FX_PROVIDER_FEE_EXPENSE: "payment.fx.provider_fee_expense",
    PAYMENT_FX_ADJUSTMENT_CHARGE: "payment.fx.adjustment.charge",
    PAYMENT_FX_ADJUSTMENT_REFUND: "payment.fx.adjustment.refund",
    PAYMENT_FX_ADJUSTMENT_CHARGE_RESERVE: "payment.fx.adjustment.charge_reserve",
    PAYMENT_FX_ADJUSTMENT_REFUND_RESERVE: "payment.fx.adjustment.refund_reserve",
    PAYMENT_FX_PAYOUT_OBLIGATION: "payment.fx.payout_obligation",
    PAYMENT_PAYOUT_INITIATE: "payment.payout.initiate",
    PAYMENT_PAYOUT_SETTLE: "payment.payout.settle",
    PAYMENT_PAYOUT_VOID: "payment.payout.void",
    PAYMENT_FEE_PAYOUT_INITIATE: "payment.fee_payout.initiate",
    PAYMENT_FEE_PAYOUT_SETTLE: "payment.fee_payout.settle",
    PAYMENT_FEE_PAYOUT_VOID: "payment.fee_payout.void",
};
