export declare const DOCUMENT_MODULE_ID: {
    readonly TRANSFER: "transfer";
    readonly TRANSFER_SETTLE: "transfer_settle";
    readonly TRANSFER_VOID: "transfer_void";
    readonly PAYMENT_CASE: "payment_case";
    readonly PAYIN_FUNDING: "payin_funding";
    readonly FX_EXECUTE: "fx_execute";
    readonly PAYOUT_INITIATE: "payout_initiate";
    readonly PAYOUT_SETTLE: "payout_settle";
    readonly PAYOUT_VOID: "payout_void";
    readonly FEE_PAYOUT_INITIATE: "fee_payout_initiate";
    readonly FEE_PAYOUT_SETTLE: "fee_payout_settle";
    readonly FEE_PAYOUT_VOID: "fee_payout_void";
    readonly EXTERNAL_FUNDING: "external_funding";
};
export type DocumentModuleId = (typeof DOCUMENT_MODULE_ID)[keyof typeof DOCUMENT_MODULE_ID];
export declare const OPERATION_CODE: {
    readonly TRANSFER_APPROVE_IMMEDIATE_INTRA: "TRANSFER_APPROVE_IMMEDIATE_INTRA";
    readonly TRANSFER_APPROVE_PENDING_INTRA: "TRANSFER_APPROVE_PENDING_INTRA";
    readonly TRANSFER_APPROVE_IMMEDIATE_CROSS: "TRANSFER_APPROVE_IMMEDIATE_CROSS";
    readonly TRANSFER_APPROVE_PENDING_CROSS: "TRANSFER_APPROVE_PENDING_CROSS";
    readonly TRANSFER_SETTLE_PENDING: "TRANSFER_SETTLE_PENDING";
    readonly TRANSFER_VOID_PENDING: "TRANSFER_VOID_PENDING";
    readonly TREASURY_FUNDING_SETTLED: "TREASURY_FUNDING_SETTLED";
    readonly TREASURY_EXTERNAL_FUNDING: "TREASURY_EXTERNAL_FUNDING";
    readonly TREASURY_FX_EXECUTED: "TREASURY_FX_EXECUTED";
    readonly TREASURY_PAYOUT_INIT: "TREASURY_PAYOUT_INIT";
    readonly TREASURY_PAYOUT_SETTLE: "TREASURY_PAYOUT_SETTLE";
    readonly TREASURY_PAYOUT_VOID: "TREASURY_PAYOUT_VOID";
    readonly TREASURY_FEE_PAYMENT_INIT: "TREASURY_FEE_PAYMENT_INIT";
    readonly TREASURY_FEE_PAYMENT_SETTLE: "TREASURY_FEE_PAYMENT_SETTLE";
    readonly TREASURY_FEE_PAYMENT_VOID: "TREASURY_FEE_PAYMENT_VOID";
};
export type OperationCode = (typeof OPERATION_CODE)[keyof typeof OPERATION_CODE];
export declare const POSTING_TEMPLATE_KEY: {
    readonly TRANSFER_INTRA_IMMEDIATE: "transfer.intra.immediate";
    readonly TRANSFER_INTRA_PENDING: "transfer.intra.pending";
    readonly TRANSFER_CROSS_SOURCE_IMMEDIATE: "transfer.cross.source.immediate";
    readonly TRANSFER_CROSS_SOURCE_PENDING: "transfer.cross.source.pending";
    readonly TRANSFER_CROSS_DESTINATION_IMMEDIATE: "transfer.cross.destination.immediate";
    readonly TRANSFER_CROSS_DESTINATION_PENDING: "transfer.cross.destination.pending";
    readonly TRANSFER_PENDING_SETTLE: "transfer.pending.settle";
    readonly TRANSFER_PENDING_VOID: "transfer.pending.void";
    readonly EXTERNAL_FUNDING_FOUNDER_EQUITY: "external_funding.founder_equity";
    readonly EXTERNAL_FUNDING_INVESTOR_EQUITY: "external_funding.investor_equity";
    readonly EXTERNAL_FUNDING_SHAREHOLDER_LOAN: "external_funding.shareholder_loan";
    readonly EXTERNAL_FUNDING_OPENING_BALANCE: "external_funding.opening_balance";
    readonly PAYMENT_PAYIN_FUNDING: "payment.payin_funding";
    readonly PAYMENT_FX_PRINCIPAL: "payment.fx.principal";
    readonly PAYMENT_FX_LEG_OUT: "payment.fx.leg_out";
    readonly PAYMENT_FX_LEG_IN: "payment.fx.leg_in";
    readonly PAYMENT_FX_FEE_INCOME: "payment.fx.fee_income";
    readonly PAYMENT_FX_SPREAD_INCOME: "payment.fx.spread_income";
    readonly PAYMENT_FX_FEE_RESERVE: "payment.fx.fee_reserve";
    readonly PAYMENT_FX_PROVIDER_FEE_EXPENSE: "payment.fx.provider_fee_expense";
    readonly PAYMENT_FX_ADJUSTMENT_CHARGE: "payment.fx.adjustment.charge";
    readonly PAYMENT_FX_ADJUSTMENT_REFUND: "payment.fx.adjustment.refund";
    readonly PAYMENT_FX_ADJUSTMENT_CHARGE_RESERVE: "payment.fx.adjustment.charge_reserve";
    readonly PAYMENT_FX_ADJUSTMENT_REFUND_RESERVE: "payment.fx.adjustment.refund_reserve";
    readonly PAYMENT_FX_PAYOUT_OBLIGATION: "payment.fx.payout_obligation";
    readonly PAYMENT_PAYOUT_INITIATE: "payment.payout.initiate";
    readonly PAYMENT_PAYOUT_SETTLE: "payment.payout.settle";
    readonly PAYMENT_PAYOUT_VOID: "payment.payout.void";
    readonly PAYMENT_FEE_PAYOUT_INITIATE: "payment.fee_payout.initiate";
    readonly PAYMENT_FEE_PAYOUT_SETTLE: "payment.fee_payout.settle";
    readonly PAYMENT_FEE_PAYOUT_VOID: "payment.fee_payout.void";
};
export type PostingTemplateKey = (typeof POSTING_TEMPLATE_KEY)[keyof typeof POSTING_TEMPLATE_KEY];
//# sourceMappingURL=index.d.ts.map