import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "apps/api/vitest.config.ts",
      "apps/web/vitest.config.ts",
      "apps/workers/vitest.config.ts",
      "packages/adapters/auth-betterauth/vitest.config.ts",
      "packages/adapters/db-drizzle/vitest.config.ts",
      "packages/adapters/idempotency-postgres/vitest.config.ts",
      "packages/adapters/ledger-tigerbeetle/vitest.config.ts",
      "packages/adapters/worker-runtime/vitest.config.ts",
      "packages/modules/accounting/vitest.config.ts",
      "packages/modules/accounting-close/vitest.config.ts",
      "packages/modules/balances/vitest.config.ts",
      "packages/modules/currencies/vitest.config.ts",
      "packages/modules/documents/vitest.config.ts",
      "packages/modules/fees/vitest.config.ts",
      "packages/modules/fx/vitest.config.ts",
      "packages/modules/identity/vitest.config.ts",
      "packages/modules/ledger/vitest.config.ts",
      "packages/modules/counterparties/vitest.config.ts",
      "packages/modules/customers/vitest.config.ts",
      "packages/modules/organizations/vitest.config.ts",
      "packages/modules/requisites/vitest.config.ts",
      "packages/modules/reconciliation/vitest.config.ts",
      "packages/modules/users/vitest.config.ts",
      "packages/extensions/documents-commercial/vitest.config.ts",
      "packages/extensions/documents-ifrs/vitest.config.ts",
      "packages/extensions/documents-sdk/vitest.config.ts",
      "packages/foundation/core/vitest.config.ts",
      "packages/foundation/money/vitest.config.ts",
      "packages/foundation/observability/vitest.config.ts",
      "packages/foundation/party-types/vitest.config.ts",
      "packages/foundation/reference-data/vitest.config.ts",
      "packages/integrations/fx-providers/vitest.config.ts",
      "packages/queries/accounting-reporting/vitest.config.ts",
      "packages/workflows/period-close/vitest.config.ts",
      "ops/bootstrap/db/vitest.config.ts",
    ],
    exclude: ["**/node_modules/**", "**/dist/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: ["**/*.test.ts", "**/*.spec.ts"],
    },
  },
});
