import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "tests/guardrails/vitest.config.ts",
      "apps/api/vitest.config.ts",
      "apps/db/vitest.config.ts",
      "apps/web/vitest.config.ts",
      "apps/workers/vitest.config.ts",
      "packages/modules/accounting/vitest.config.ts",
      "packages/modules/balances/vitest.config.ts",
      "packages/modules/currencies/vitest.config.ts",
      "packages/modules/documents/vitest.config.ts",
      "packages/modules/fees/vitest.config.ts",
      "packages/modules/fx/vitest.config.ts",
      "packages/modules/ledger/vitest.config.ts",
      "packages/modules/organizations/vitest.config.ts",
      "packages/modules/parties/vitest.config.ts",
      "packages/modules/reconciliation/vitest.config.ts",
      "packages/modules/requisites/vitest.config.ts",
      "packages/modules/users/vitest.config.ts",
      "packages/platform/vitest.config.ts",
      "packages/plugins/documents-commercial/vitest.config.ts",
      "packages/plugins/documents-ifrs/vitest.config.ts",
      "packages/plugins/documents-sdk/vitest.config.ts",
      "packages/shared/vitest.config.ts",
      "packages/workflows/document-drafts/vitest.config.ts",
      "packages/workflows/document-posting/vitest.config.ts",
      "packages/workflows/organization-bootstrap/vitest.config.ts",
      "packages/workflows/period-close/vitest.config.ts",
      "packages/workflows/reconciliation-adjustments/vitest.config.ts",
      "packages/workflows/requisite-accounting/vitest.config.ts",
    ],
    exclude: ["**/node_modules/**", "**/dist/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: ["**/*.test.ts", "**/*.spec.ts"],
    },
  },
});
