import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "apps/api/vitest.config.ts",
      "apps/web/vitest.config.ts",
      "apps/workers/vitest.config.ts",
      "packages/modules/accounting/vitest.config.ts",
      "packages/modules/balances/vitest.config.ts",
      "packages/modules/counterparties/vitest.config.ts",
      "packages/modules/currencies/vitest.config.ts",
      "packages/modules/customers/vitest.config.ts",
      "packages/modules/documents/vitest.config.ts",
      "packages/modules/fees/vitest.config.ts",
      "packages/modules/fx/vitest.config.ts",
      "packages/modules/ledger/vitest.config.ts",
      "packages/modules/organizations/vitest.config.ts",
      "packages/modules/reconciliation/vitest.config.ts",
      "packages/modules/requisites/vitest.config.ts",
      "packages/modules/users/vitest.config.ts",
      "packages/platform/auth-betterauth/vitest.config.ts",
      "packages/platform/auth-model/vitest.config.ts",
      "packages/platform/idempotency-postgres/vitest.config.ts",
      "packages/platform/observability/vitest.config.ts",
      "packages/platform/persistence/vitest.config.ts",
      "packages/platform/postgres/vitest.config.ts",
      "packages/platform/worker-runtime/vitest.config.ts",
      "packages/plugins/documents-commercial/vitest.config.ts",
      "packages/plugins/documents-ifrs/vitest.config.ts",
      "packages/plugins/documents-sdk/vitest.config.ts",
      "packages/shared/core/vitest.config.ts",
      "packages/shared/money/vitest.config.ts",
      "packages/shared/reference-data/vitest.config.ts",
      "packages/workflows/period-close/vitest.config.ts",
      "ops/bootstrap/db/vitest.config.ts",
    ],
    exclude: ["**/node_modules/**", "**/dist/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: ["**/*.test.ts", "**/*.spec.ts"],
    },
  },
});
