export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
    textOperators: [
        { label: "Содержит", value: "iLike" as const },
        { label: "Не содержит", value: "notILike" as const },
        { label: "Равно", value: "eq" as const },
        { label: "Не равно", value: "ne" as const },
        { label: "Пусто", value: "isEmpty" as const },
        { label: "Не пусто", value: "isNotEmpty" as const },
    ],
    numericOperators: [
        { label: "Равно", value: "eq" as const },
        { label: "Не равно", value: "ne" as const },
        { label: "Меньше", value: "lt" as const },
        { label: "Меньше или равно", value: "lte" as const },
        { label: "Больше", value: "gt" as const },
        { label: "Больше или равно", value: "gte" as const },
        { label: "Между", value: "isBetween" as const },
        { label: "Пусто", value: "isEmpty" as const },
        { label: "Не пусто", value: "isNotEmpty" as const },
    ],
    dateOperators: [
        { label: "Равно", value: "eq" as const },
        { label: "Is not", value: "ne" as const },
        { label: "Is before", value: "lt" as const },
        { label: "Is after", value: "gt" as const },
        { label: "Is on or before", value: "lte" as const },
        { label: "Is on or after", value: "gte" as const },
        { label: "Is between", value: "isBetween" as const },
        { label: "Is relative to today", value: "isRelativeToToday" as const },
        { label: "Is empty", value: "isEmpty" as const },
        { label: "Is not empty", value: "isNotEmpty" as const },
    ],
    selectOperators: [
        { label: "Равно", value: "eq" as const },
        { label: "Не равно", value: "ne" as const },
        { label: "Пусто", value: "isEmpty" as const },
        { label: "Не пусто", value: "isNotEmpty" as const },
    ],
    multiSelectOperators: [
        { label: "Содержит любое из", value: "inArray" as const },
        { label: "Не содержит любое из", value: "notInArray" as const },
        { label: "Пусто", value: "isEmpty" as const },
        { label: "Не пусто", value: "isNotEmpty" as const },
    ],
    booleanOperators: [
        { label: "Равно", value: "eq" as const },
        { label: "Не равно", value: "ne" as const },
    ],
    sortOrders: [
        { label: "По возрастанию", value: "asc" as const },
        { label: "По убыванию", value: "desc" as const },
    ],
    filterVariants: [
        "text",
        "number",
        "range",
        "date",
        "dateRange",
        "boolean",
        "select",
        "multiSelect",
    ] as const,
    operators: [
        "iLike",
        "notILike",
        "eq",
        "ne",
        "inArray",
        "notInArray",
        "isEmpty",
        "isNotEmpty",
        "lt",
        "lte",
        "gt",
        "gte",
        "isBetween",
        "isRelativeToToday",
    ] as const,
    joinOperators: ["and", "or"] as const,
};