services:
  postgres:
    image: postgres:17
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/${DB_NAME}:/var/lib/postgresql/data

  tigerbeetle:
    build:
      context: ./tigerbeetle
      dockerfile: Dockerfile
    container_name: bedrock-tigerbeetle
    ports:
      - "3555:3000"
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    cap_add:
      - IPC_LOCK
