import type { Database, Transaction } from "@bedrock/adapter-db-drizzle/client";
import { schema } from "@bedrock/adapter-db-drizzle";

const ACCOUNTS = [
  ["1000", "Активы", "asset", "debit", false, true, null],
  [
    "1100",
    "Денежные средства и эквиваленты",
    "asset",
    "debit",
    false,
    true,
    "1000",
  ],
  ["1200", "Операционные активы", "asset", "debit", false, true, "1000"],
  [
    "1300",
    "Внутригрупповые расчеты",
    "active_passive",
    "both",
    false,
    true,
    "1000",
  ],
  ["2000", "Обязательства", "liability", "credit", false, true, null],
  [
    "2100",
    "Операционные обязательства",
    "liability",
    "credit",
    false,
    true,
    "2000",
  ],
  [
    "2210",
    "Займ от учредителя/инвестора",
    "liability",
    "credit",
    true,
    true,
    "2000",
  ],
  ["3000", "Капитал", "equity", "credit", false, true, null],
  ["3110", "Вклад учредителя", "equity", "credit", true, true, "3000"],
  ["3120", "Инвестиции в капитал", "equity", "credit", true, true, "3000"],
  ["3200", "Балансирующий капитал", "equity", "credit", true, true, "3000"],
  ["4000", "Доходы", "revenue", "credit", false, true, null],
  ["5000", "Расходы", "expense", "debit", false, true, null],
  ["1110", "Банк", "asset", "debit", true, true, "1100"],
  ["1220", "Транзит", "asset", "debit", true, true, "1200"],
  ["1310", "Клиринг", "active_passive", "both", true, true, "1300"],
  ["2110", "Кошелек клиента", "liability", "credit", true, true, "2100"],
  ["2120", "Клиринг комиссий", "liability", "credit", true, true, "2100"],
  [
    "2130",
    "Обязательство по выплате",
    "liability",
    "credit",
    true,
    true,
    "2100",
  ],
  ["2140", "Резерв по ордерам", "liability", "credit", true, true, "2100"],
  ["4110", "Доход от комиссий", "revenue", "credit", true, true, "4000"],
  ["4120", "Доход от спреда", "revenue", "credit", true, true, "4000"],
  ["4130", "Доход от корректировок", "revenue", "credit", true, true, "4000"],
  ["5110", "Расход по корректировкам", "expense", "debit", true, true, "5000"],
  [
    "5120",
    "Расход по комиссии провайдера",
    "expense",
    "debit",
    true,
    true,
    "5000",
  ],
] as const;

const RULES = [
  ["TR.INTRA.IMMEDIATE", "1110", "1110"],
  ["TR.INTRA.PENDING", "1110", "1110"],
  ["TR.CROSS.SOURCE.IMMEDIATE", "1310", "1110"],
  ["TR.CROSS.DEST.IMMEDIATE", "1110", "1310"],
  ["TR.CROSS.SOURCE.PENDING", "1310", "1110"],
  ["TR.CROSS.DEST.PENDING", "1110", "1310"],
  ["TC.2101", "1310", "1110"],
  ["TC.2102", "1110", "1310"],
  ["TC.2103", "1310", "1110"],
  ["TC.2104", "1110", "1310"],
  ["TC.1001", "1110", "2110"],
  ["TC.9001", "1110", "3110"],
  ["TC.9002", "1110", "3120"],
  ["TC.9003", "1110", "2210"],
  ["TC.9004", "1110", "2110"],
  ["TC.9005", "1110", "3200"],
  ["TC.2001", "2110", "2140"],
  ["TC.2009", "2140", "1310"],
  ["TC.2010", "1310", "2140"],
  ["TC.2005", "2140", "2130"],
  ["TC.3001", "2110", "4110"],
  ["TC.3002", "2110", "4120"],
  ["TC.3003", "2110", "2120"],
  ["TC.3004", "2120", "4110"],
  ["TC.3005", "2120", "4120"],
  ["TC.3008", "5120", "2120"],
  ["TC.3009", "2120", "4130"],
  ["TC.3010", "5110", "2120"],
  ["TC.3101", "2130", "1110"],
  ["TC.3011", "2120", "1110"],
  ["TC.3201", "1310", "4110"],
  ["TC.3202", "1310", "4120"],
  ["TC.3203", "1310", "2120"],
  ["TC.3203", "2120", "1310"],
  ["TC.3204", "5120", "1310"],
  ["TC.3204", "1310", "5120"],
  ["TC.3205", "1310", "4130"],
  ["TC.3206", "5110", "1310"],
  ["TC.3006", "2110", "4130"],
  ["TC.3007", "5110", "2110"],
] as const;

// [accountNo, dimensionKey, mode]
const ACCOUNT_DIMENSION_POLICIES = [
  // BANK
  ["1110", "organizationRequisiteId", "required"],
  ["1110", "orderId", "forbidden"],
  ["1110", "customerId", "forbidden"],
  ["1110", "feeBucket", "forbidden"],
  ["1110", "clearingKind", "forbidden"],
  ["1110", "counterpartyId", "forbidden"],
  // CUSTOMER_WALLET
  ["2110", "customerId", "required"],
  ["2110", "organizationRequisiteId", "forbidden"],
  ["2110", "feeBucket", "forbidden"],
  ["2110", "clearingKind", "forbidden"],
  // CLEARING (1310)
  ["1310", "clearingKind", "required"],
  ["1310", "counterpartyId", "optional"],
  ["1310", "orderId", "optional"],
  ["1310", "organizationRequisiteId", "forbidden"],
  ["1310", "feeBucket", "forbidden"],
  ["1310", "customerId", "forbidden"],
  // ORDER_RESERVE
  ["2140", "orderId", "required"],
  ["2140", "customerId", "optional"],
  ["2140", "organizationRequisiteId", "forbidden"],
  ["2140", "feeBucket", "forbidden"],
  ["2140", "clearingKind", "forbidden"],
  // FEE_CLEARING
  ["2120", "feeBucket", "required"],
  ["2120", "orderId", "required"],
  ["2120", "counterpartyId", "optional"],
  ["2120", "organizationRequisiteId", "forbidden"],
  ["2120", "clearingKind", "forbidden"],
  ["2120", "customerId", "forbidden"],
  // PAYOUT_OBLIGATION
  ["2130", "orderId", "required"],
  ["2130", "counterpartyId", "optional"],
  ["2130", "organizationRequisiteId", "forbidden"],
  ["2130", "feeBucket", "forbidden"],
  ["2130", "clearingKind", "forbidden"],
  ["2130", "customerId", "forbidden"],
  // SHAREHOLDER_LOAN (2210)
  ["2210", "counterpartyId", "required"],
  ["2210", "organizationRequisiteId", "forbidden"],
  ["2210", "orderId", "forbidden"],
  ["2210", "customerId", "forbidden"],
  ["2210", "feeBucket", "forbidden"],
  ["2210", "clearingKind", "forbidden"],
  // FOUNDER_EQUITY (3110)
  ["3110", "counterpartyId", "required"],
  ["3110", "organizationRequisiteId", "forbidden"],
  ["3110", "orderId", "forbidden"],
  ["3110", "customerId", "forbidden"],
  ["3110", "feeBucket", "forbidden"],
  ["3110", "clearingKind", "forbidden"],
  // INVESTOR_EQUITY (3120)
  ["3120", "counterpartyId", "required"],
  ["3120", "organizationRequisiteId", "forbidden"],
  ["3120", "orderId", "forbidden"],
  ["3120", "customerId", "forbidden"],
  ["3120", "feeBucket", "forbidden"],
  ["3120", "clearingKind", "forbidden"],
  // PROVIDER_FEE_EXPENSE
  ["5120", "feeBucket", "required"],
  ["5120", "orderId", "required"],
  ["5120", "counterpartyId", "optional"],
] as const;

// [postingCode, dimensionKey, required, scope]
const POSTING_CODE_DIMENSION_POLICIES = [
  ["TR.INTRA.IMMEDIATE", "organizationRequisiteId", true, "line"],
  ["TR.INTRA.PENDING", "organizationRequisiteId", true, "line"],
  ["TR.CROSS.SOURCE.IMMEDIATE", "counterpartyId", true, "debit"],
  ["TR.CROSS.SOURCE.IMMEDIATE", "organizationRequisiteId", true, "credit"],
  ["TR.CROSS.DEST.IMMEDIATE", "counterpartyId", true, "credit"],
  ["TR.CROSS.DEST.IMMEDIATE", "organizationRequisiteId", true, "debit"],
  ["TR.CROSS.SOURCE.PENDING", "counterpartyId", true, "debit"],
  ["TR.CROSS.SOURCE.PENDING", "organizationRequisiteId", true, "credit"],
  ["TR.CROSS.DEST.PENDING", "counterpartyId", true, "credit"],
  ["TR.CROSS.DEST.PENDING", "organizationRequisiteId", true, "debit"],
  ["TC.2101", "orderId", true, "debit"],
  ["TC.2101", "clearingKind", true, "debit"],
  ["TC.2101", "organizationRequisiteId", true, "credit"],
  ["TC.2102", "organizationRequisiteId", true, "debit"],
  ["TC.2102", "orderId", true, "credit"],
  ["TC.2102", "clearingKind", true, "credit"],
  ["TC.2103", "orderId", true, "debit"],
  ["TC.2103", "clearingKind", true, "debit"],
  ["TC.2103", "organizationRequisiteId", true, "credit"],
  ["TC.2104", "organizationRequisiteId", true, "debit"],
  ["TC.2104", "orderId", true, "credit"],
  ["TC.2104", "clearingKind", true, "credit"],
  ["TC.1001", "customerId", true, "credit"],
  ["TC.1001", "organizationRequisiteId", true, "debit"],
  ["TC.9001", "organizationRequisiteId", true, "debit"],
  ["TC.9001", "counterpartyId", true, "credit"],
  ["TC.9002", "organizationRequisiteId", true, "debit"],
  ["TC.9002", "counterpartyId", true, "credit"],
  ["TC.9003", "organizationRequisiteId", true, "debit"],
  ["TC.9003", "counterpartyId", true, "credit"],
  ["TC.9004", "organizationRequisiteId", true, "debit"],
  ["TC.9004", "customerId", true, "credit"],
  ["TC.9005", "organizationRequisiteId", true, "debit"],
  ["TC.2001", "orderId", true, "credit"],
  ["TC.2001", "customerId", true, "debit"],
  ["TC.2009", "orderId", true, "line"],
  ["TC.2009", "counterpartyId", true, "credit"],
  ["TC.2009", "clearingKind", true, "credit"],
  ["TC.2010", "orderId", true, "line"],
  ["TC.2010", "counterpartyId", true, "debit"],
  ["TC.2010", "clearingKind", true, "debit"],
  ["TC.2005", "orderId", true, "line"],
  ["TC.3001", "orderId", true, "line"],
  ["TC.3001", "customerId", true, "debit"],
  ["TC.3001", "feeBucket", true, "line"],
  ["TC.3002", "orderId", true, "line"],
  ["TC.3002", "customerId", true, "debit"],
  ["TC.3002", "feeBucket", true, "line"],
  ["TC.3004", "orderId", true, "line"],
  ["TC.3004", "feeBucket", true, "line"],
  ["TC.3005", "orderId", true, "line"],
  ["TC.3005", "feeBucket", true, "line"],
  ["TC.3003", "orderId", true, "line"],
  ["TC.3003", "feeBucket", true, "line"],
  ["TC.3008", "orderId", true, "line"],
  ["TC.3008", "feeBucket", true, "line"],
  ["TC.3008", "counterpartyId", true, "line"],
  ["TC.3011", "orderId", true, "debit"],
  ["TC.3011", "feeBucket", true, "debit"],
  ["TC.3011", "counterpartyId", true, "debit"],
  ["TC.3011", "organizationRequisiteId", true, "credit"],
  ["TC.3201", "orderId", true, "line"],
  ["TC.3201", "feeBucket", true, "credit"],
  ["TC.3201", "clearingKind", true, "debit"],
  ["TC.3202", "orderId", true, "line"],
  ["TC.3202", "feeBucket", true, "credit"],
  ["TC.3202", "clearingKind", true, "debit"],
  ["TC.3203", "orderId", true, "line"],
  ["TC.3203", "feeBucket", true, "credit"],
  ["TC.3203", "clearingKind", true, "debit"],
  ["TC.3204", "orderId", true, "line"],
  ["TC.3204", "feeBucket", true, "debit"],
  ["TC.3204", "clearingKind", true, "credit"],
  ["TC.3205", "orderId", true, "line"],
  ["TC.3205", "feeBucket", true, "credit"],
  ["TC.3205", "clearingKind", true, "debit"],
  ["TC.3206", "orderId", true, "line"],
  ["TC.3206", "feeBucket", true, "debit"],
  ["TC.3206", "clearingKind", true, "credit"],
  ["TC.3101", "orderId", true, "debit"],
  ["TC.3101", "organizationRequisiteId", true, "credit"],
  ["TC.3006", "orderId", true, "line"],
  ["TC.3006", "customerId", true, "debit"],
  ["TC.3006", "feeBucket", true, "line"],
  ["TC.3007", "orderId", true, "line"],
  ["TC.3007", "customerId", true, "credit"],
  ["TC.3007", "feeBucket", true, "line"],
  ["TC.3009", "orderId", true, "line"],
  ["TC.3009", "feeBucket", true, "line"],
  ["TC.3010", "orderId", true, "line"],
  ["TC.3010", "feeBucket", true, "line"],
] as const;

const REPORT_LINE_MAPPINGS = [
  [
    "ifrs",
    "balance_sheet",
    "BS.CASH_EQUIV",
    "Cash and cash equivalents",
    "assets",
    "1110",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.TRANSIT",
    "Transit balances",
    "assets",
    "1220",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.CLEARING",
    "Clearing balances",
    "assets",
    "1310",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.CUSTOMER_WALLET",
    "Customer wallet liabilities",
    "liabilities",
    "2110",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.FEE_CLEARING",
    "Fee clearing liabilities",
    "liabilities",
    "2120",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.PAYOUT_OBLIGATION",
    "Payout obligations",
    "liabilities",
    "2130",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.ORDER_RESERVE",
    "Order reserves",
    "liabilities",
    "2140",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.SHAREHOLDER_LOAN",
    "Shareholder loan",
    "liabilities",
    "2210",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.FOUNDER_EQUITY",
    "Founder equity",
    "equity",
    "3110",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.INVESTOR_EQUITY",
    "Investor equity",
    "equity",
    "3120",
    1,
  ],
  [
    "ifrs",
    "balance_sheet",
    "BS.OPENING_BAL_EQ",
    "Opening balance equity",
    "equity",
    "3200",
    1,
  ],
  [
    "ifrs",
    "income_statement",
    "IS.FEE_REVENUE",
    "Fee revenue",
    "revenue",
    "4110",
    1,
  ],
  [
    "ifrs",
    "income_statement",
    "IS.SPREAD_REVENUE",
    "Spread revenue",
    "revenue",
    "4120",
    1,
  ],
  [
    "ifrs",
    "income_statement",
    "IS.ADJ_REVENUE",
    "Adjustment revenue",
    "revenue",
    "4130",
    1,
  ],
  [
    "ifrs",
    "income_statement",
    "IS.ADJ_EXPENSE",
    "Adjustment expense",
    "expense",
    "5110",
    1,
  ],
  [
    "ifrs",
    "income_statement",
    "IS.PROVIDER_FEE_EXPENSE",
    "Provider fee expense",
    "expense",
    "5120",
    1,
  ],
  [
    "ifrs",
    "cash_flow_direct",
    "CFD.OPERATING_CASH",
    "Operating cash flow",
    "operating",
    "1110",
    1,
  ],
  [
    "ifrs",
    "cash_flow_indirect",
    "CFI.WORKING_CAPITAL",
    "Working capital adjustment",
    "adjustments",
    "2140",
    1,
  ],
  [
    "ifrs",
    "fx_revaluation",
    "FX.REVALUATION",
    "FX revaluation",
    "revaluation",
    "4130",
    1,
  ],
  [
    "ifrs",
    "fx_revaluation",
    "FX.REVALUATION_EXPENSE",
    "FX revaluation expense",
    "revaluation",
    "5110",
    1,
  ],
  [
    "ifrs",
    "fee_revenue",
    "FEE.REVENUE",
    "Fee revenue",
    "revenue",
    "4110",
    1,
  ],
  [
    "ifrs",
    "fee_revenue",
    "FEE.SPREAD",
    "Spread revenue",
    "revenue",
    "4120",
    1,
  ],
  [
    "ifrs",
    "fee_revenue",
    "FEE.PROVIDER_EXPENSE",
    "Provider fee expense",
    "expense",
    "5120",
    1,
  ],
] as const;

export async function seedAccounting(db: Database | Transaction) {
  for (const [
    accountNo,
    name,
    kind,
    normalSide,
    postingAllowed,
    enabled,
    parentAccountNo,
  ] of ACCOUNTS) {
    await db
      .insert(schema.chartTemplateAccounts)
      .values({
        accountNo,
        name,
        kind,
        normalSide,
        postingAllowed,
        enabled,
        parentAccountNo,
      })
      .onConflictDoUpdate({
        target: schema.chartTemplateAccounts.accountNo,
        set: {
          name,
          kind,
          normalSide,
          postingAllowed,
          enabled,
          parentAccountNo,
        },
      });
  }

  for (const [postingCode, debitAccountNo, creditAccountNo] of RULES) {
    await db
      .insert(schema.correspondenceRules)
      .values({
        postingCode,
        debitAccountNo,
        creditAccountNo,
        enabled: true,
      })
      .onConflictDoUpdate({
        target: [
          schema.correspondenceRules.postingCode,
          schema.correspondenceRules.debitAccountNo,
          schema.correspondenceRules.creditAccountNo,
        ],
        set: { enabled: true },
      });
  }

  for (const [accountNo, dimensionKey, mode] of ACCOUNT_DIMENSION_POLICIES) {
    await db
      .insert(schema.chartAccountDimensionPolicy)
      .values({
        accountNo,
        dimensionKey,
        mode,
      })
      .onConflictDoUpdate({
        target: [
          schema.chartAccountDimensionPolicy.accountNo,
          schema.chartAccountDimensionPolicy.dimensionKey,
        ],
        set: { mode },
      });
  }

  for (const [
    postingCode,
    dimensionKey,
    required,
    scope,
  ] of POSTING_CODE_DIMENSION_POLICIES) {
    await db
      .insert(schema.postingCodeDimensionPolicy)
      .values({
        postingCode,
        dimensionKey,
        required,
        scope,
      })
      .onConflictDoUpdate({
        target: [
          schema.postingCodeDimensionPolicy.postingCode,
          schema.postingCodeDimensionPolicy.dimensionKey,
        ],
        set: { required, scope },
      });
  }

  for (const [
    standard,
    reportKind,
    lineCode,
    lineLabel,
    section,
    accountNo,
    signMultiplier,
  ] of REPORT_LINE_MAPPINGS) {
    await db
      .insert(schema.accountingReportLineMappings)
      .values({
        standard,
        reportKind,
        lineCode,
        lineLabel,
        section,
        accountNo,
        signMultiplier,
      })
      .onConflictDoNothing();
  }
}
