import {
  counterpartyEndpoints,
  treasuryAccountBalanceEntries,
  treasuryAccounts,
  treasuryAllocations,
  treasuryDocumentLinks,
  treasuryEndpoints,
  treasuryExecutionEvents,
  treasuryExecutionInstructions,
  treasuryObligations,
  treasuryOperationObligations,
  treasuryOperations,
  treasuryPositions,
} from "./core/adapters/drizzle/schema";
import { feeRules } from "./fees/adapters/drizzle/schema";
import {
  fxQuoteFeeComponents,
  fxQuoteFinancialLines,
  fxQuoteLegs,
  fxQuotes,
} from "./quotes/adapters/drizzle/schema";
import { fxRateSources, fxRates } from "./rates/adapters/drizzle/schema";

export {
  counterpartyEndpoints,
  feeRules,
  fxQuoteFeeComponents,
  fxQuoteFinancialLines,
  fxQuoteLegs,
  fxQuotes,
  fxRateSources,
  fxRates,
  treasuryAccountBalanceEntries,
  treasuryAccounts,
  treasuryAllocations,
  treasuryDocumentLinks,
  treasuryEndpoints,
  treasuryExecutionEvents,
  treasuryExecutionInstructions,
  treasuryObligations,
  treasuryOperationObligations,
  treasuryOperations,
  treasuryPositions,
};

export const schema = {
  counterpartyEndpoints,
  fxQuotes,
  fxQuoteLegs,
  fxQuoteFeeComponents,
  fxQuoteFinancialLines,
  fxRates,
  fxRateSources,
  feeRules,
  treasuryAccounts,
  treasuryEndpoints,
  treasuryObligations,
  treasuryOperations,
  treasuryOperationObligations,
  treasuryExecutionInstructions,
  treasuryExecutionEvents,
  treasuryAllocations,
  treasuryPositions,
  treasuryAccountBalanceEntries,
  treasuryDocumentLinks,
};
