export const ACCOUNT_NO = {
  ASSETS: "1000",
  CASH_AND_EQUIVALENTS: "1100",
  OPERATING_ASSETS: "1200",
  INTERCOMPANY_ASSETS: "1300",
  LIABILITIES: "2000",
  OPERATING_LIABILITIES: "2100",
  EQUITY: "3000",
  REVENUES: "4000",
  EXPENSES: "5000",

  BANK: "1110",
  ORDER_INVENTORY: "1210",
  TRANSIT: "1220",
  INTERCOMPANY_NET: "1310",
  CUSTOMER_WALLET: "2110",
  FEE_CLEARING: "2120",
  PAYOUT_OBLIGATION: "2130",
  FEE_REVENUE: "4110",
  SPREAD_REVENUE: "4120",
  ADJUSTMENT_REVENUE: "4130",
  ADJUSTMENT_EXPENSE: "5110",
} as const;

export const OPERATION_CODE = {
  TRANSFER_APPROVE_IMMEDIATE_INTRA: "TRANSFER_APPROVE_IMMEDIATE_INTRA",
  TRANSFER_APPROVE_PENDING_INTRA: "TRANSFER_APPROVE_PENDING_INTRA",
  TRANSFER_APPROVE_IMMEDIATE_CROSS: "TRANSFER_APPROVE_IMMEDIATE_CROSS",
  TRANSFER_APPROVE_PENDING_CROSS: "TRANSFER_APPROVE_PENDING_CROSS",
  TRANSFER_SETTLE_PENDING: "TRANSFER_SETTLE_PENDING",
  TRANSFER_VOID_PENDING: "TRANSFER_VOID_PENDING",

  TREASURY_FUNDING_SETTLED: "TREASURY_FUNDING_SETTLED",
  TREASURY_FX_EXECUTED: "TREASURY_FX_EXECUTED",
  TREASURY_PAYOUT_INIT: "TREASURY_PAYOUT_INIT",
  TREASURY_PAYOUT_SETTLE: "TREASURY_PAYOUT_SETTLE",
  TREASURY_PAYOUT_VOID: "TREASURY_PAYOUT_VOID",
  TREASURY_FEE_PAYMENT_INIT: "TREASURY_FEE_PAYMENT_INIT",
  TREASURY_FEE_PAYMENT_SETTLE: "TREASURY_FEE_PAYMENT_SETTLE",
  TREASURY_FEE_PAYMENT_VOID: "TREASURY_FEE_PAYMENT_VOID",
} as const;

export const POSTING_CODE = {
  // Transfers
  TRANSFER_INTRA_IMMEDIATE: "TR.INTRA.IMMEDIATE",
  TRANSFER_INTRA_PENDING: "TR.INTRA.PENDING",
  TRANSFER_CROSS_SOURCE_IMMEDIATE: "TR.CROSS.SOURCE.IMMEDIATE",
  TRANSFER_CROSS_DEST_IMMEDIATE: "TR.CROSS.DEST.IMMEDIATE",
  TRANSFER_CROSS_SOURCE_PENDING: "TR.CROSS.SOURCE.PENDING",
  TRANSFER_CROSS_DEST_PENDING: "TR.CROSS.DEST.PENDING",

  // Treasury / transfer code mapping
  FUNDING_SETTLED: "TC.1001",
  FX_PRINCIPAL: "TC.2001",
  FEE_REVENUE: "TC.2002",
  SPREAD_REVENUE: "TC.2003",
  FX_INTERCOMPANY_COMMIT: "TC.2004",
  FX_PAYOUT_OBLIGATION: "TC.2005",
  BANK_FEE_REVENUE: "TC.2006",
  BLOCKCHAIN_FEE_REVENUE: "TC.2007",
  ARBITRARY_FEE_REVENUE: "TC.2008",
  FX_LEG_OUT: "TC.2009",
  FX_LEG_IN: "TC.2010",
  PAYOUT_INITIATED: "TC.3001",
  FEE_SEPARATE_PAYMENT_RESERVE: "TC.3002",
  FEE_PAYMENT_INITIATED: "TC.3003",
  FEE_PAYMENT_SETTLED: "TC.3004",
  FEE_PAYMENT_VOIDED: "TC.3005",
  ADJUSTMENT_CHARGE: "TC.3006",
  ADJUSTMENT_REFUND: "TC.3007",
  INTERNAL_TRANSFER: "TC.4001",
} as const;

export type PostingCode = (typeof POSTING_CODE)[keyof typeof POSTING_CODE];

export const DEFAULT_CHART_TEMPLATE_ACCOUNTS = [
  {
    accountNo: ACCOUNT_NO.ASSETS,
    name: "Активы",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.CASH_AND_EQUIVALENTS,
    name: "Денежные средства и эквиваленты",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.OPERATING_ASSETS,
    name: "Операционные активы",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.INTERCOMPANY_ASSETS,
    name: "Внутригрупповые расчеты",
    kind: "active_passive",
    normalSide: "both",
    postingAllowed: false,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.LIABILITIES,
    name: "Обязательства",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: false,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
    name: "Операционные обязательства",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: false,
    parentAccountNo: ACCOUNT_NO.LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.EQUITY,
    name: "Капитал",
    kind: "equity",
    normalSide: "credit",
    postingAllowed: false,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.REVENUES,
    name: "Доходы",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: false,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.EXPENSES,
    name: "Расходы",
    kind: "expense",
    normalSide: "debit",
    postingAllowed: false,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.BANK,
    name: "Банк",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.CASH_AND_EQUIVALENTS,
  },
  {
    accountNo: ACCOUNT_NO.ORDER_INVENTORY,
    name: "Резерв по ордерам",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.TRANSIT,
    name: "Транзит",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.INTERCOMPANY_NET,
    name: "Внутригрупповой неттинг",
    kind: "active_passive",
    normalSide: "both",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.INTERCOMPANY_ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    name: "Кошелек клиента",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.FEE_CLEARING,
    name: "Клиринг комиссий",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
    name: "Обязательство по выплате",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.FEE_REVENUE,
    name: "Доход от комиссий",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.SPREAD_REVENUE,
    name: "Доход от спреда",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.ADJUSTMENT_REVENUE,
    name: "Доход от корректировок",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.ADJUSTMENT_EXPENSE,
    name: "Расход по корректировкам",
    kind: "expense",
    normalSide: "debit",
    postingAllowed: true,
    parentAccountNo: ACCOUNT_NO.EXPENSES,
  },
] as const;

export const DEFAULT_CHART_TEMPLATE_ACCOUNT_ANALYTICS = [
  {
    accountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    analyticType: "customer_id",
    required: true,
  },
  {
    accountNo: ACCOUNT_NO.ORDER_INVENTORY,
    analyticType: "order_id",
    required: true,
  },
  {
    accountNo: ACCOUNT_NO.FEE_CLEARING,
    analyticType: "fee_bucket",
    required: true,
  },
  {
    accountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
    analyticType: "order_id",
    required: true,
  },
  {
    accountNo: ACCOUNT_NO.INTERCOMPANY_NET,
    analyticType: "counterparty_id",
    required: true,
  },
] as const;

export const DEFAULT_GLOBAL_CORRESPONDENCE_RULES = [
  {
    postingCode: POSTING_CODE.TRANSFER_INTRA_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_INTRA_PENDING,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_PENDING,
    debitAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_PENDING,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
  },
  {
    postingCode: POSTING_CODE.FUNDING_SETTLED,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
  },
  {
    postingCode: POSTING_CODE.FX_PRINCIPAL,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.ORDER_INVENTORY,
  },
  {
    postingCode: POSTING_CODE.FX_LEG_OUT,
    debitAccountNo: ACCOUNT_NO.ORDER_INVENTORY,
    creditAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
  },
  {
    postingCode: POSTING_CODE.FX_LEG_IN,
    debitAccountNo: ACCOUNT_NO.INTERCOMPANY_NET,
    creditAccountNo: ACCOUNT_NO.ORDER_INVENTORY,
  },
  {
    postingCode: POSTING_CODE.FEE_REVENUE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_REVENUE,
  },
  {
    postingCode: POSTING_CODE.SPREAD_REVENUE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.SPREAD_REVENUE,
  },
  {
    postingCode: POSTING_CODE.BANK_FEE_REVENUE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_REVENUE,
  },
  {
    postingCode: POSTING_CODE.BLOCKCHAIN_FEE_REVENUE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_REVENUE,
  },
  {
    postingCode: POSTING_CODE.ARBITRARY_FEE_REVENUE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_REVENUE,
  },
  {
    postingCode: POSTING_CODE.FX_PAYOUT_OBLIGATION,
    debitAccountNo: ACCOUNT_NO.ORDER_INVENTORY,
    creditAccountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
  },
  {
    postingCode: POSTING_CODE.PAYOUT_INITIATED,
    debitAccountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED,
    debitAccountNo: ACCOUNT_NO.FEE_CLEARING,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.ADJUSTMENT_CHARGE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.ADJUSTMENT_REVENUE,
  },
  {
    postingCode: POSTING_CODE.ADJUSTMENT_REFUND,
    debitAccountNo: ACCOUNT_NO.ADJUSTMENT_EXPENSE,
    creditAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
  },
  {
    postingCode: POSTING_CODE.FEE_SEPARATE_PAYMENT_RESERVE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_CLEARING,
  },
  {
    postingCode: POSTING_CODE.FEE_SEPARATE_PAYMENT_RESERVE,
    debitAccountNo: ACCOUNT_NO.ADJUSTMENT_EXPENSE,
    creditAccountNo: ACCOUNT_NO.FEE_CLEARING,
  },
] as const;
