export const ACCOUNT_NO = {
  ASSETS: "1000",
  CASH_AND_EQUIVALENTS: "1100",
  OPERATING_ASSETS: "1200",
  INTERCOMPANY_ASSETS: "1300",
  LIABILITIES: "2000",
  OPERATING_LIABILITIES: "2100",
  EQUITY: "3000",
  REVENUES: "4000",
  EXPENSES: "5000",

  BANK: "1110",
  TRANSIT: "1220",
  CLEARING: "1300",
  CUSTOMER_WALLET: "2110",
  FEE_CLEARING: "2120",
  PAYOUT_OBLIGATION: "2130",
  ORDER_RESERVE: "2140",
  FEE_REVENUE: "4110",
  SPREAD_REVENUE: "4120",
  ADJUSTMENT_REVENUE: "4130",
  ADJUSTMENT_EXPENSE: "5110",
  PROVIDER_FEE_EXPENSE: "5120",
} as const;

export const CLEARING_KIND = {
  INTERCOMPANY: "intercompany",
  TREASURY_FX: "treasury_fx",
} as const;

export const OPERATION_CODE = {
  TRANSFER_APPROVE_IMMEDIATE_INTRA: "TRANSFER_APPROVE_IMMEDIATE_INTRA",
  TRANSFER_APPROVE_PENDING_INTRA: "TRANSFER_APPROVE_PENDING_INTRA",
  TRANSFER_APPROVE_IMMEDIATE_CROSS: "TRANSFER_APPROVE_IMMEDIATE_CROSS",
  TRANSFER_APPROVE_PENDING_CROSS: "TRANSFER_APPROVE_PENDING_CROSS",
  TRANSFER_SETTLE_PENDING: "TRANSFER_SETTLE_PENDING",
  TRANSFER_VOID_PENDING: "TRANSFER_VOID_PENDING",

  TREASURY_FUNDING_SETTLED: "TREASURY_FUNDING_SETTLED",
  TREASURY_FX_EXECUTED: "TREASURY_FX_EXECUTED",
  TREASURY_PAYOUT_INIT: "TREASURY_PAYOUT_INIT",
  TREASURY_PAYOUT_SETTLE: "TREASURY_PAYOUT_SETTLE",
  TREASURY_PAYOUT_VOID: "TREASURY_PAYOUT_VOID",
  TREASURY_FEE_PAYMENT_INIT: "TREASURY_FEE_PAYMENT_INIT",
  TREASURY_FEE_PAYMENT_SETTLE: "TREASURY_FEE_PAYMENT_SETTLE",
  TREASURY_FEE_PAYMENT_VOID: "TREASURY_FEE_PAYMENT_VOID",
} as const;

export const POSTING_CODE = {
  TRANSFER_INTRA_IMMEDIATE: "TR.INTRA.IMMEDIATE",
  TRANSFER_INTRA_PENDING: "TR.INTRA.PENDING",
  TRANSFER_CROSS_SOURCE_IMMEDIATE: "TR.CROSS.SOURCE.IMMEDIATE",
  TRANSFER_CROSS_DEST_IMMEDIATE: "TR.CROSS.DEST.IMMEDIATE",
  TRANSFER_CROSS_SOURCE_PENDING: "TR.CROSS.SOURCE.PENDING",
  TRANSFER_CROSS_DEST_PENDING: "TR.CROSS.DEST.PENDING",

  FUNDING_SETTLED: "TC.1001",
  FX_PRINCIPAL: "TC.2001",
  FX_PAYOUT_OBLIGATION: "TC.2005",
  FX_LEG_OUT: "TC.2009",
  FX_LEG_IN: "TC.2010",

  FEE_INCOME: "TC.3001",
  SPREAD_INCOME: "TC.3002",
  FEE_PASS_THROUGH_RESERVE: "TC.3003",
  ADJUSTMENT_CHARGE: "TC.3006",
  ADJUSTMENT_REFUND: "TC.3007",
  PROVIDER_FEE_EXPENSE_ACCRUAL: "TC.3008",
  FEE_PAYMENT_INITIATED: "TC.3011",
  PAYOUT_INITIATED: "TC.3101",
} as const;

export type DimensionMode = "required" | "optional" | "forbidden";

export interface AccountDimensionPolicy {
  accountNo: string;
  dimensionKey: string;
  mode: DimensionMode;
}

export interface PostingCodeDimensionPolicyEntry {
  postingCode: string;
  dimensionKey: string;
  required: boolean;
}

export const DEFAULT_CHART_TEMPLATE_ACCOUNTS = [
  {
    accountNo: ACCOUNT_NO.ASSETS,
    name: "Активы",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.CASH_AND_EQUIVALENTS,
    name: "Денежные средства и эквиваленты",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.OPERATING_ASSETS,
    name: "Операционные активы",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.CLEARING,
    name: "Clearing",
    kind: "active_passive",
    normalSide: "both",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.LIABILITIES,
    name: "Обязательства",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
    name: "Операционные обязательства",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.EQUITY,
    name: "Капитал",
    kind: "equity",
    normalSide: "credit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.REVENUES,
    name: "Доходы",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.EXPENSES,
    name: "Расходы",
    kind: "expense",
    normalSide: "debit",
    postingAllowed: false,
    enabled: true,
    parentAccountNo: null,
  },
  {
    accountNo: ACCOUNT_NO.BANK,
    name: "Банк",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.CASH_AND_EQUIVALENTS,
  },
  {
    accountNo: ACCOUNT_NO.TRANSIT,
    name: "Транзит",
    kind: "asset",
    normalSide: "debit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_ASSETS,
  },
  {
    accountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    name: "Кошелек клиента",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.FEE_CLEARING,
    name: "Клиринг комиссий",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
    name: "Обязательство по выплате",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.ORDER_RESERVE,
    name: "ORDER_RESERVE",
    kind: "liability",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.OPERATING_LIABILITIES,
  },
  {
    accountNo: ACCOUNT_NO.FEE_REVENUE,
    name: "Доход от комиссий",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.SPREAD_REVENUE,
    name: "Доход от спреда",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.ADJUSTMENT_REVENUE,
    name: "Доход от корректировок",
    kind: "revenue",
    normalSide: "credit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.REVENUES,
  },
  {
    accountNo: ACCOUNT_NO.ADJUSTMENT_EXPENSE,
    name: "Расход по корректировкам",
    kind: "expense",
    normalSide: "debit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.EXPENSES,
  },
  {
    accountNo: ACCOUNT_NO.PROVIDER_FEE_EXPENSE,
    name: "PROVIDER_FEE_EXPENSE",
    kind: "expense",
    normalSide: "debit",
    postingAllowed: true,
    enabled: true,
    parentAccountNo: ACCOUNT_NO.EXPENSES,
  },
] as const;

export const DEFAULT_ACCOUNT_DIMENSION_POLICIES: AccountDimensionPolicy[] = [
  { accountNo: ACCOUNT_NO.BANK, dimensionKey: "operationalAccountId", mode: "required" },
  { accountNo: ACCOUNT_NO.CUSTOMER_WALLET, dimensionKey: "customerId", mode: "required" },
  { accountNo: ACCOUNT_NO.CLEARING, dimensionKey: "clearingKind", mode: "required" },
  { accountNo: ACCOUNT_NO.CLEARING, dimensionKey: "counterpartyId", mode: "optional" },
  { accountNo: ACCOUNT_NO.CLEARING, dimensionKey: "orderId", mode: "optional" },
  { accountNo: ACCOUNT_NO.FEE_CLEARING, dimensionKey: "feeBucket", mode: "required" },
  { accountNo: ACCOUNT_NO.FEE_CLEARING, dimensionKey: "orderId", mode: "required" },
  { accountNo: ACCOUNT_NO.FEE_CLEARING, dimensionKey: "counterpartyId", mode: "optional" },
  { accountNo: ACCOUNT_NO.PAYOUT_OBLIGATION, dimensionKey: "orderId", mode: "required" },
  { accountNo: ACCOUNT_NO.ORDER_RESERVE, dimensionKey: "orderId", mode: "required" },
  { accountNo: ACCOUNT_NO.ORDER_RESERVE, dimensionKey: "customerId", mode: "optional" },
  { accountNo: ACCOUNT_NO.PROVIDER_FEE_EXPENSE, dimensionKey: "feeBucket", mode: "required" },
  { accountNo: ACCOUNT_NO.PROVIDER_FEE_EXPENSE, dimensionKey: "orderId", mode: "required" },
  { accountNo: ACCOUNT_NO.PROVIDER_FEE_EXPENSE, dimensionKey: "counterpartyId", mode: "optional" },
];

export const DEFAULT_POSTING_CODE_DIMENSION_POLICIES: PostingCodeDimensionPolicyEntry[] = [
  { postingCode: POSTING_CODE.TRANSFER_INTRA_IMMEDIATE, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_INTRA_PENDING, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_IMMEDIATE, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_IMMEDIATE, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_IMMEDIATE, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_IMMEDIATE, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_PENDING, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_PENDING, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_PENDING, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_PENDING, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.FUNDING_SETTLED, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.FUNDING_SETTLED, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.FX_PRINCIPAL, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FX_PRINCIPAL, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.FX_LEG_OUT, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FX_LEG_OUT, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.FX_LEG_OUT, dimensionKey: "clearingKind", required: true },
  { postingCode: POSTING_CODE.FX_LEG_IN, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FX_LEG_IN, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.FX_LEG_IN, dimensionKey: "clearingKind", required: true },
  { postingCode: POSTING_CODE.FX_PAYOUT_OBLIGATION, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FEE_INCOME, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FEE_INCOME, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.FEE_INCOME, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.SPREAD_INCOME, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.SPREAD_INCOME, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.SPREAD_INCOME, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.FEE_PASS_THROUGH_RESERVE, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FEE_PASS_THROUGH_RESERVE, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.FEE_PASS_THROUGH_RESERVE, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.PROVIDER_FEE_EXPENSE_ACCRUAL, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.PROVIDER_FEE_EXPENSE_ACCRUAL, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.PROVIDER_FEE_EXPENSE_ACCRUAL, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.PAYOUT_INITIATED, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.PAYOUT_INITIATED, dimensionKey: "counterpartyId", required: true },
  { postingCode: POSTING_CODE.PAYOUT_INITIATED, dimensionKey: "operationalAccountId", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_CHARGE, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_CHARGE, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_CHARGE, dimensionKey: "feeBucket", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_REFUND, dimensionKey: "orderId", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_REFUND, dimensionKey: "customerId", required: true },
  { postingCode: POSTING_CODE.ADJUSTMENT_REFUND, dimensionKey: "feeBucket", required: true },
];

export const DEFAULT_GLOBAL_CORRESPONDENCE_RULES = [
  {
    postingCode: POSTING_CODE.TRANSFER_INTRA_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_INTRA_PENDING,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.CLEARING,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_IMMEDIATE,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.CLEARING,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_SOURCE_PENDING,
    debitAccountNo: ACCOUNT_NO.CLEARING,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.TRANSFER_CROSS_DEST_PENDING,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.CLEARING,
  },
  {
    postingCode: POSTING_CODE.FUNDING_SETTLED,
    debitAccountNo: ACCOUNT_NO.BANK,
    creditAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
  },
  {
    postingCode: POSTING_CODE.FX_PRINCIPAL,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.ORDER_RESERVE,
  },
  {
    postingCode: POSTING_CODE.FX_LEG_OUT,
    debitAccountNo: ACCOUNT_NO.ORDER_RESERVE,
    creditAccountNo: ACCOUNT_NO.CLEARING,
  },
  {
    postingCode: POSTING_CODE.FX_LEG_IN,
    debitAccountNo: ACCOUNT_NO.CLEARING,
    creditAccountNo: ACCOUNT_NO.ORDER_RESERVE,
  },
  {
    postingCode: POSTING_CODE.FX_PAYOUT_OBLIGATION,
    debitAccountNo: ACCOUNT_NO.ORDER_RESERVE,
    creditAccountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
  },
  {
    postingCode: POSTING_CODE.FEE_INCOME,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_REVENUE,
  },
  {
    postingCode: POSTING_CODE.SPREAD_INCOME,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.SPREAD_REVENUE,
  },
  {
    postingCode: POSTING_CODE.FEE_PASS_THROUGH_RESERVE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.FEE_CLEARING,
  },
  {
    postingCode: POSTING_CODE.PROVIDER_FEE_EXPENSE_ACCRUAL,
    debitAccountNo: ACCOUNT_NO.PROVIDER_FEE_EXPENSE,
    creditAccountNo: ACCOUNT_NO.FEE_CLEARING,
  },
  {
    postingCode: POSTING_CODE.FEE_PAYMENT_INITIATED,
    debitAccountNo: ACCOUNT_NO.FEE_CLEARING,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.PAYOUT_INITIATED,
    debitAccountNo: ACCOUNT_NO.PAYOUT_OBLIGATION,
    creditAccountNo: ACCOUNT_NO.BANK,
  },
  {
    postingCode: POSTING_CODE.ADJUSTMENT_CHARGE,
    debitAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
    creditAccountNo: ACCOUNT_NO.ADJUSTMENT_REVENUE,
  },
  {
    postingCode: POSTING_CODE.ADJUSTMENT_REFUND,
    debitAccountNo: ACCOUNT_NO.ADJUSTMENT_EXPENSE,
    creditAccountNo: ACCOUNT_NO.CUSTOMER_WALLET,
  },
] as const;
