import {
  dealAgentBonuses,
  dealApprovalStatusEnum,
  dealApprovalTypeEnum,
  dealApprovals,
  dealCalculationLinks,
  dealLegKindEnum,
  dealLegStateEnum,
  dealLegs,
  dealIntakeSnapshots,
  dealParticipantRoleEnum,
  dealParticipants,
  deals,
  dealStatusEnum,
  dealTimelineEventTypeEnum,
  dealTimelineEvents,
  dealTimelineVisibilityEnum,
  dealQuoteAcceptances,
  dealTypeEnum,
} from "./adapters/drizzle/schema";

export {
  dealAgentBonuses,
  dealApprovalStatusEnum,
  dealApprovalTypeEnum,
  dealApprovals,
  dealCalculationLinks,
  dealLegKindEnum,
  dealLegStateEnum,
  dealLegs,
  dealIntakeSnapshots,
  dealParticipantRoleEnum,
  dealParticipants,
  deals,
  dealStatusEnum,
  dealTimelineEventTypeEnum,
  dealTimelineEvents,
  dealTimelineVisibilityEnum,
  dealQuoteAcceptances,
  dealTypeEnum,
};

export const schema = {
  deals,
  dealIntakeSnapshots,
  dealLegs,
  dealParticipants,
  dealTimelineEvents,
  dealAgentBonuses,
  dealApprovals,
  dealCalculationLinks,
  dealQuoteAcceptances,
  dealTypeEnum,
  dealStatusEnum,
  dealLegKindEnum,
  dealLegStateEnum,
  dealParticipantRoleEnum,
  dealTimelineEventTypeEnum,
  dealTimelineVisibilityEnum,
  dealApprovalTypeEnum,
  dealApprovalStatusEnum,
};
