import {
  dealAgentBonuses,
  dealApprovalStatusEnum,
  dealApprovalTypeEnum,
  dealApprovals,
  dealCalculationLinks,
  dealExtensions,
  dealLegKindEnum,
  dealLegs,
  dealParticipantRoleEnum,
  dealParticipants,
  deals,
  dealStatusEnum,
  dealStatusHistory,
  dealTypeEnum,
} from "./adapters/drizzle/schema";

export {
  dealAgentBonuses,
  dealApprovalStatusEnum,
  dealApprovalTypeEnum,
  dealApprovals,
  dealCalculationLinks,
  dealExtensions,
  dealLegKindEnum,
  dealLegs,
  dealParticipantRoleEnum,
  dealParticipants,
  deals,
  dealStatusEnum,
  dealStatusHistory,
  dealTypeEnum,
};

export const schema = {
  deals,
  dealLegs,
  dealParticipants,
  dealStatusHistory,
  dealAgentBonuses,
  dealApprovals,
  dealCalculationLinks,
  dealExtensions,
  dealTypeEnum,
  dealStatusEnum,
  dealLegKindEnum,
  dealParticipantRoleEnum,
  dealApprovalTypeEnum,
  dealApprovalStatusEnum,
};
